version: "3.5"

services:
  vacancy_backend:
    build: .
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    environment:
      DB_HOST: vacancy_db
      DB_NAME: vacancy
      DB_USER: vacancy
      DB_PASS: hunter2
    links:
      - vacancy_db
    command: ["yarn", "prod"]
  vacancy_db:
    image: postgres:latest
    volumes:
      - vacancy-db:/var/lib/postgresql/data

volumes:
  vacancy-db: {}
